#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from service.ttypes import *

PolicyDepart = {
    715: "国家级,中华人民共和国工业和信息化部",
    716: "国家级,财政部",
    717: "国家级,中华人民共和国科学技术部",
    718: "国家级,中华人民共和国商业部",
    719: "国家级,国家改革和发展委员会",
    720: "国家级,中华人民共和国人力资源和社会保障部",
    923: "国家级,国家部委级政策"
}